version: '3'

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/usr/local/etc/redis

  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566-4583:4566-4583
    volumes:
      - localstack_volume:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_volume:
  redis_volume:
  localstack_volume:
